//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobRecurring.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cast
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cast()
        {
            this.CastMappings = new HashSet<CastMapping>();
        }
    
        public int Id { get; set; }
        public string Avatar { get; set; }
        public string AvatarThumb { get; set; }
        public Nullable<int> AvatarId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Description { get; set; }
        public string Country { get; set; }
        public string SearchText { get; set; }
        public string Link { get; set; }
        public string SeoTitle { get; set; }
        public string SeoDescription { get; set; }
        public Nullable<int> LikeNumber { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string CdnAvatar { get; set; }
        public string CdnAvatarThumb { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CastMapping> CastMappings { get; set; }
    }
}
