//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobRecurring.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie()
        {
            this.CastMappings = new HashSet<CastMapping>();
            this.CategoryMappings = new HashSet<CategoryMapping>();
            this.Episodes = new HashSet<Episode>();
            this.MovieRates = new HashSet<MovieRate>();
            this.MovieViews = new HashSet<MovieView>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string OtherName { get; set; }
        public string Avatar { get; set; }
        public Nullable<int> AvatarId { get; set; }
        public string Panner { get; set; }
        public Nullable<int> PannerId { get; set; }
        public string Description { get; set; }
        public Nullable<int> EpisodesTotal { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Year { get; set; }
        public string Language { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Director { get; set; }
        public string Time { get; set; }
        public string Trailer { get; set; }
        public string Link { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<bool> ShowTop { get; set; }
        public Nullable<bool> ShowCenter { get; set; }
        public Nullable<bool> IsPublish { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public string ShowTimes { get; set; }
        public string SearchText { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public string SeoTitle { get; set; }
        public string SeoDescription { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<int> LikeNumber { get; set; }
        public Nullable<int> ViewNumber { get; set; }
        public Nullable<int> RatePoint { get; set; }
        public Nullable<int> RateNumner { get; set; }
        public string Keyword { get; set; }
        public Nullable<bool> LokLokMovie { get; set; }
        public Nullable<int> LokLokMovieId { get; set; }
        public Nullable<int> LokLokCategoryId { get; set; }
        public string StatusTitle { get; set; }
        public string SeoKeywords { get; set; }
        public string CDNAvatar { get; set; }
        public string CDNBanner { get; set; }
        public string OriginalLink { get; set; }
        public Nullable<bool> DMCA { get; set; }
        public Nullable<bool> Tvhay { get; set; }
        public string CastString { get; set; }
        public Nullable<bool> IsRecurring { get; set; }
        public string RecurringURL { get; set; }
        public Nullable<System.DateTime> RecurringTime { get; set; }
        public string RecurringRepeat { get; set; }
        public string DaysOfWeek { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CastMapping> CastMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryMapping> CategoryMappings { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Episode> Episodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieRate> MovieRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieView> MovieViews { get; set; }
    }
}
