//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobRecurring.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public System.Guid Guid { get; set; }
        public string Username { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<decimal> Money { get; set; }
        public Nullable<decimal> TotalMoney { get; set; }
        public string Address { get; set; }
        public string Address1 { get; set; }
        public string Company { get; set; }
        public string TaxNumber { get; set; }
        public string LastIp { get; set; }
        public bool IsSystemAccount { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> CannotLoginUntilDate { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string RoleId { get; set; }
        public string Avatar { get; set; }
        public string TokenLogin { get; set; }
    }
}
